# docker-compose.yml
version: "3.8"

services:
  db: # Имя вашего сервиса базы данных
    image: postgres # Используем официальный образ PostgreSQL (версия 16, легкий Alpine-вариант)
    container_name: todo-postgresql # Удобное имя для контейнера
    environment:
      POSTGRES_DB: todo-app-db # Имя базы данных, которую создастся при первом запуске
      POSTGRES_USER: myuser # Имя пользователя для подключения к БД
      POSTGRES_PASSWORD: mypassword # Пароль для пользователя БД
      # PGDATA: /var/lib/postgresql/data/pgdata # Можно указать кастомный путь внутри контейнера для данных
    volumes:
      - postgres_data:/var/lib/postgresql/data # Маппинг данных: сохраняем данные в Docker Volume
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Опционально: для выполнения SQL-скриптов при первом запуске
    ports:
      - "5432:5432" # Пробрасываем порт PostgreSQL контейнера на хост-машину
    restart: always # Всегда перезапускать контейнер, если он падает

volumes:
  postgres_data: # Объявление именованного тома для постоянного хранения данных
